repo_url: "https://grldadrcks.github.io/fdroid-repo/repo"
repo_name: "Mason's F-Droid Repo"
repo_description: "Personal F-Droid repository."
keystore: "keystore.jks"
# keystorepass, keypass, and keyalias are injected by GitHub Actions from Secrets
